NFL_TEAM = {
    "Arizona":"ARI",
    "Atlanta":"ATL",
    "Baltimore":"BAL",
    "Buffalo":"BUF",
    "Carolina":"CAR",
    "Chicago":"CHI",
    "Cincinnati":"CIN",
    "Cleveland":"CLE",
    "Dallas":"DAL",
    "Denver":"DEN",
    "Detroit":"DET",
    "Green Bay":"GB",
    "Houston":"HOU",
    "Indianapolis":"IND",
    "Jacksonville":"JAX",
    "Kansas City":"KC",
    "Miami":"MIA",
    "Minnesota":"MIN",
    "New England":"NE",
    "New Orleans":"NO",
    "N.Y. Giants":"NYG",
    "N.Y. Jets":"NYJ",
    "Las Vegas":"LV",
    "L.A. Chargers":"LAC",
    "L.A. Rams":"LAR",
    "Philadelphia":"PHI",
    "Pittsburgh":"PIT",
    "San Francisco":"SF",
    "Seattle":"SEA",
    "Tampa Bay":"TB",
    "Tennessee":"TEN",
    "Washington":"WAS"
}